server {
    listen 80;
    server_name _;
    include /etc/nginx/mime.types;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html /index.html;
    }

    location ~* \.(?:css|js|svg|png|jpg|jpeg|gif|woff2?|ttf|ico)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
    }
}
